### ISSUE TITLE
Crockford modified - origins?

### ISSUE THREAD

**Issue by MartinFalatic** [alanblevins/anybase32#1]
Do you happen to know anything about the origin and use of the modified Crockford alphabet?

`b"0123456789abcdefghjkmnpqrtuvwxyz"`

I have stumbled on it in a few places (where the encoding didn't come out quite as one would expect with the usual Crockford translation) but I can't find a canonical source for this modified version alphabet and why it even exists.

**Comment by alanblevins** [comment]
I'm afraid I don't know how that alphabet came about. 

Interestingly enough, this package started as a way to translate modified Crockford, because I found an interface that was outputting base32 using that alphabet and there didn't seem to be any existing Python packages that handled it natively. And then I thought this might be more useful as a generalized implementation rather than just supporting modified Crockford, and here we are...

**Comment by MartinFalatic** [comment]
I managed to back-calculate it based on the weird output I was getting from one online tool, but I don't know why anyone uses it. Then I found yours so at least someone acknowledges it's unusual. Thanks!
